routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('frontend.index');
//})->name('home');
//


Route::get('/', 'FrontendController@index')->name('home');
Route::get('posts', 'PostController@index')->name('post.index');
Route::get('post/{slug}', 'PostController@details')->name('post.details');
Route::get('category/{slug}', 'PostController@postBycategory')->name('category.posts');
Route::get('tag/{slug}', 'PostController@postByTag')->name('tag.posts');
Route::get('profile/{username}', 'AuthorController@profile')->name('author.profile');

Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');
Route::get('/search', 'SearchController@search')->name('search');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

    Route::post('/favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}', 'CommentController@store')->name('comment.store');
});

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');


    Route::get('settings', 'SettingsController@index')->name('settings');


    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');


    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');


    Route::get('/pending/post', 'PostController@pending')->name('post.pending');
    Route::put('/post/{id}/approve', 'PostController@approval')->name('post.approve');
    Route::get('/favorite', 'FavoriteController@index')->name('favorite');
    Route::get('authors', 'AuthorController@index')->name('author.index');
    Route::delete('authors/{id}', 'AuthorController@destroy')->name('author.destroy');



    Route::get('comments', 'CommentController@index')->name('comment.index');
    Route::delete('comments/{id}/', 'CommentController@destroy')->name('comment.destroy');



    Route::get('/subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}', 'SubscriberController@destroy')->name('subsrciber.destroy');


});


Route::group(['as' => 'author.', 'prefix' => 'author', 'namespace' => 'Author', 'middleware' => ['auth', 'author']], function () {


    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('post', 'PostController');
    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::get('/favorite', 'FavoriteController@index')->name('favorite');
    Route::get('comments', 'CommentController@index')->name('comment.index');
    Route::delete('comments/{id}/', 'CommentController@destroy')->name('comment.destroy');

});


View::composer('frontend.layouts.partials.footer',function ($view){

    $tags= App\Tag::all();
    $view->with('tags',$tags);

});

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AuthorController extends Controller
{
    public function index(){


         $authors= User::authors()
            ->withCount('posts')
            ->withCount('comments')
            ->withCount('favorite_posts')
            ->get();
         return view('admin.authors',compact('authors'));
    }

    public function destroy($id){


        $author= User::findOrFail($id);
        $author->delete();
        Toastr::success('Author Successfully Deleted :)','Success');
        return redirect()
            ->back();


    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Notifications\AuthorPostApproved;
use App\Notifications\NewPostNotify;
use App\Post;
use App\Subscriber;
use App\Tag;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    const UPLOAD_DIR = '/uploads/post/';

    public function index()
    {
        $posts = Post::latest()->get();
        return view('admin.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin.post.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'image' => 'required|mimes:jpg,png,jpeg',
            'categories' => 'required',
            'tags' => 'required',
            'body' => 'required',
        ]);


        $data = new Post();
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $name = date('y-m-d') . '_' . str_slug($request->title) . '.' . $image->getClientOriginalExtension($image);
            $destinationPath = public_path('/uploads/post');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $data->image = $name;
        }
        $data->user_id = Auth::id();
        $data->title = $request->title;
        $slug = Str::slug($request->title);
        $data->image = $data['image'];
        $data->slug = $slug;
        $data->body = $request->body;
        if (isset($request->status)) {
            $data->status = true;
        } else {
            $data->status = false;
        }
        $data->is_approved = true;
        $data->save();
        $data->categories()->attach($request->categories);
        $data->tags()->attach($request->tags);
        $subscribers=Subscriber::all();
        foreach ($subscribers as $subscriber)
        {
            Notification::route('mail',$subscriber->email)
                ->notify(new NewPostNotify($data));
        }

        Toastr::success('Post Successfully Inserted :)', 'Success');
        return redirect()
            ->route('admin.post.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('admin.post.show', compact('post'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin.post.edit', compact('post', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'categories' => 'required',
            'tags' => 'required',
            'body' => 'required',
        ]);


        $data = new Post();
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $name = date('y-m-d') . '_' . str_slug($request->title) . '.' . $image->getClientOriginalExtension($image);
            $destinationPath = public_path('/uploads/post');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $data->image = $name;
        } else {
            $data->image = $post->image;
        }
        $data->user_id = Auth::id();
        $data->title = $request->title;
        $slug = Str::slug($request->title);
        $data->image = $data['image'];
        $data->slug = $slug;
        $data->body = $request->body;
        if (isset($request->status)) {
            $data->status = true;
        } else {
            $data->status = false;
        }
        $data->is_approved = true;
        $data->save();
        $data->categories()->sync($request->categories);
        $data->tags()->sync($request->tags);


        Toastr::success('Post Successfully Updated :)', 'Success');
        return redirect()
            ->route('admin.post.index');
    }


    public function pending()
    {
        $posts = Post::where('is_approved', false)->get();
        return view('admin.post.pending', compact('posts'));
    }

    public function approval($id)
    {
        $post= Post::findOrFail($id);
        if($post->is_approved == false){

            $post->is_approved = true;
            $post->save();

            $post->user->notify(new AuthorPostApproved($post));
            $subscribers=Subscriber::all();
        foreach ($subscribers as $subscriber)
        {
            Notification::route('mail',$subscriber->email)
                ->notify(new NewPostNotify($post));
        }


            Toastr::success('Post Successfully Approved :)', 'Success');


        }else{
            Toastr::success('This post is already approved :)', 'Info');

        }
        return redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if ($post->image) {
            $image_path = public_path() . '/uploads/post/' . $post->image;
            unlink($image_path);

        } else {

        }
        $post->categories()->detach();
        $post->tags()->detach();
        $post->delete();
        Toastr::success('Category Successfully Deleted :)', 'Success');
        return redirect()
            ->route('admin.post.index');
    }


}

app/Http/Controllers/Author/CommentController.php
<?php

namespace App\Http\Controllers\Author;

use App\Comment;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{

    public function index()
    {
        $posts = Auth::user()->posts;
        return view('author.comments', compact('posts'));
    }

    public function destroy($id)
    {


            $comment = Comment::findOrFail($id);
        if ($comment->post->user_id != Auth::id()) {


            $comment->delete();
            Toastr::success('Comment Successfully Deleted :)', 'Success');
            return redirect()->back();

        } else{
            Toastr::error('You are not authorized to delete this comment ! ', 'Access Denied !!!');
            return redirect()->back();
        }
    }
}

app/Http/Controllers/Author/DashboardController.php
<?php

namespace App\Http\Controllers\Author;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{
    public function index()

    {
        $user = Auth::user();
        $posts = $user->posts;
        $popular_posts = $user->posts()
            ->withCount('comments')
            ->withCount('favorite_to_users')
            ->orderBy('view_count', 'desc')
            ->orderBy('comments_count')
            ->orderBy('favorite_to_users_count')
            ->take(5)->get();
//        $total_pending_posts= Auth::user()->posts;
        $total_pending_posts = $posts->where('is_approved', false)->count();
        $all_views = $posts->sum('view_count');
        return view('author.dashboard',compact('posts','popular_posts','total_pending_posts','all_views'));
    }
}

app/Http/Controllers/Author/FavoriteController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class FavoriteController extends Controller
{
    public function index(){


        $posts= Auth::user()->favorite_posts;
        return view('author.favorite',compact('posts'));
    }
}

app/Http/Controllers/Author/SettingsController.php
<?php

namespace App\Http\Controllers\Author;

use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class SettingsController extends Controller

{

    const UPLOAD_DIR = '/uploads/profile/';

    public function index()
    {
        return view('author.settings');
    }

    public function updateProfile(Request $request)
    {
        $this->validate($request, [

            'name' => 'required',
            'email' => 'required|email',
        ]);



        $data = Str::slug($request->name);
        $data = User::findOrFail(Auth::id());

        if ($request->hasFile('image')) {
            $data['image'] = $this->uploadImage($request->image, $request->name);
        }

        $data->name=$request->name;
        $data->email=$request->email;
        $data->image=$data['image'];
        $data->about=$request->about;
        $data->update();
        Toastr::success('Profile Successfully Updated :)', 'Success');
        return redirect()->back();


    }

    public function updatePassword(Request $request){
        $this->validate($request, [

            'old_password' => 'required',
            'password' => 'required|confirmed',
        ]);

        $hashedPassword =Auth::user()->password;
        if (Hash::check($request->old_password,$hashedPassword)){

            if (!Hash::check($request->password,$hashedPassword)){

                $user =User::findOrFail(Auth::id());
                $user->password= Hash::make($request->password);
                $user->save();
                Toastr::success('Password Successfully Updated :)', 'Success');
                Auth::logout();
                return redirect()->back();
            }
            else
            {
                Toastr::error('New Password Cannot be the same as old password.', 'Error');
                return redirect()->back();


            }

        } else {
            Toastr::error('Current Password not match. ', 'Error');
            return redirect()->back();
        }



    }


    private function uploadImage($file, $name)
    {

        $extension = $file->getClientOriginalExtension($file);
        $fileName = date('y-m-d') . '_' . $name . '.' . $extension;
        Image::make($file)->resize(600, 600)->save(public_path() . self::UPLOAD_DIR . $fileName);


        return $fileName;
    }

}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    public function profile($username)
    {
        $author= User::where('username',$username)->first();
        $posts=$author->posts()->approved()->published()->get();
        return view('frontend.profile',compact('author','posts'));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class PostController extends Controller
{

    public function index()
    {
        $posts = Post::latest()->approved()->published()->paginate(6);
        return view('frontend.posts', compact('posts'));
    }


    public function details($slug)
    {
        $post = Post::where('slug', $slug)->approved()->published()->first();
        $blogKey = 'blog' . $post->id;
        if (!Session::has($blogKey)) {
            $post->increment('view_count');
            Session::put($blogKey, 1);
        }
        $randomposts = Post::approved()->published()->take(3)->inRandomOrder()->get();

        return view('frontend.post', compact('post', 'randomposts'));
    }

    public function postBycategory($slug)
    {

        $category = Category::where('slug', $slug)->first();
        $posts= $category->posts()->approved()->published()->get();
        return view('frontend.category', compact('category','posts'));
    }

    public function postByTag($slug)
    {

        $tag = Tag::where('slug', $slug)->first();
        $posts= $tag->posts()->approved()->published()->get();

        return view('frontend.tag', compact('tag','posts'));
    }


}

resources/views/author/post/form.blade.php
<div class="form-group form-float">
    <div class="form-line">
        <input type="file" name="image">
    </div>
</div>

<div class="form-group  form-float">
    <div class="form-line">
    {{ Form::text('title', null, [
        'class' => 'form-control',
        'id' => 'title',
    ]) }}

    {{ Form::label('Category Name',[
        'class' => 'form-label',
    ]) }}
    </div>
</div>


<div class="form-group form-float">
    <div class="form-line">
        {{ Form::file('image', null, [
            'id' => 'image',
        ]) }}
    </div>
</div>


{{ Form::button('Submit', [
    'type' => 'submit',
    'class' => 'btn btn-primary m-t-15 waves-effect',
]) }}

resources/views/author/post/index.blade.php
@extends('backend.layouts.master')
@section('title','Post')


@push('css')
<!-- JQuery DataTable Css -->
<link href="{{asset('ui/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">


@endpush

@section('content')
    <section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <h2>
                <a class="btn btn-primary waves-effect" href="{{route('author.post.create')}}">

                    <i class="material-icons">add</i>
                    <span>ADD NEW POST</span>
                </a>
            </h2>
        </div>

        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            ALL POSTS
                            <span class="badge bg-blue">{{$posts->count()}}</span>
                        </h2>
                        
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th><i class="material-icons">visibility</i></th>
                                    <th>Is Approved</th>
                                    <th>Status</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th><i class="material-icons">visibility</i></th>
                                    <th>Is Approved</th>
                                    <th>Status</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                @foreach($posts as $key=>$post)

                                    <tr>
                                        <td>{{$key +1}}</td>
                                        <td>{{str_limit($post->title,'10')}}</td>
                                        <td>{{$post->user->name}}</td>
                                        <td>{{$post->view_count}}</td>
                                        <td>
                                            @if($post->is_approved==true)
                                                <span class="badge bg-blue">Approved</span>
                                                @else
                                                <span class="badge bg-pink">Pending</span>

                                            @endif

                                        </td>
                                        <td>
                                            @if($post->status==true)
                                                <span class="badge bg-blue">Published</span>
                                                @else
                                                <span class="badge bg-pink">Pending</span>

                                            @endif

                                        </td>
                                        <td>{{$post->created_at->diffForHumans()}}</td>
                                        <td>{{$post->updated_at->diffForHumans()}}</td>
                                        <td>

                                            <a href="{{route('author.post.show',$post->id)}}"
                                               class="btn btn-info waves-effect">
                                                <i class="material-icons">visibility</i>
                                            </a>

                                            <a href="{{route('author.post.edit',$post->id)}}" class="btn btn-info waves-effect">
                                                <i class="material-icons">edit</i>
                                            </a>


                                            <button  type="button" class="btn btn-danger waves-effect" onclick="deletePost({{$post->id}})">
                                                <i class="material-icons">delete</i>
                                            </button>
                                            <form id="delete-form-{{$post->id}}" action="{{route('author.post.destroy',$post->id)}}" method="post" style="display: none">

                                                @csrf
                                                @method('DELETE')

                                            </form>
                                        </td>


                                    </tr>
                                  @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    </div>
    </section>
@endsection

@push('js') <!-- Jquery Core Js -->
<script src="{{asset('ui/backend/plugins/jquery/jquery.min.js')}}"></script>

<!-- Bootstrap Core Js -->
<script src="{{asset('ui/backend/plugins/bootstrap/js/bootstrap.js')}}"></script>

<!-- Select Plugin Js -->
<script src="{{asset('ui/backend/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>

<!-- Slimscroll Plugin Js -->
<script src="{{asset('ui/backend/plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></script>

<!-- Waves Effect Plugin Js -->
<script src="{{asset('ui/backend/plugins/node-waves/waves.js')}}"></script>

<!-- Jquery DataTable Plugin Js -->
<script src="{{asset('ui/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
<script src="{{asset('ui/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
<script src="{{asset('ui/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('ui/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
<script src="{{asset('ui/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
<script src="{{asset('ui/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
<script src="{{asset('ui/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
<script src="{{asset('ui/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
<script src="{{asset('ui/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

<!-- Custom Js -->
<script src="{{asset('ui/backend/js/admin.js')}}"></script>
<script src="{{asset('ui/backend/js/pages/tables/jquery-datatable.js')}}"></script>

<!-- Demo Js -->
<script src="{{asset('ui/backend/js/demo.js')}}"></script>


<script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>


<script type="text/javascript">

    function deletePost(id) {
        Swal.fire({
            title: 'Are you sure?',
            text: 'You will not be able to recover this Tag!',
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, keep it'
        }).then((result) => {
            if (result.value) {
            Swal.fire(

                event.preventDefault(),
                document.getElementById('delete-form-'+id).submit()
            )
            // For more information about handling dismissals please visit
            // https://sweetalert2.github.io/#handling-dismissals
        } else if (result.dismiss === Swal.DismissReason.cancel) {
            Swal.fire(
                'Cancelled',
                'Your Data is safe :)',
                'error'
            )
        }
    });
    }
</script>
@endpush

resources/views/author/post/show.blade.php
@extends('backend.layouts.master')
@section('title','Post')


@push('css')
<!-- Bootstrap Select Css -->
<link href="{{asset('ui/backend/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet"/>

@endpush

@section('content')
    <section class="content">
        <div class="container-fluid">
            <a href="{{route('author.post.index')}}" class="btn btn-danger waves-effect">Back</a>
            @if($post->is_approved == false)
                <button type="button" class="btn btn-danger waves-effect pull-right">
                    <i class="material-icons">pending</i>
                    <span>Pending</span>
                </button>
            @else
                <button type="button" class="btn btn-success waves-effect pull-right" disabled="disabled">
                    <i class="material-icons">done</i>
                    <span>Approved</span>
                </button>
            @endif

            <br><br>
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                {{$post->title}}
                                <small>Posted by
                                    <strong>
                                        <a href="">{{$post->user->name}}</a>
                                    </strong> on {{$post->created_at->toFormattedDateString()}}
                                </small>
                            </h2>
                        </div>
                        <div class="body">
                            {!! $post->body!!}

                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header bg-red">
                            <h2>
                                CATEGORIES
                            </h2>
                        </div>
                        <div class="body">

                            @foreach($post->categories as $category)
                                <span class="label bg-cyan" style="font-size: 13px">{{$category->name}}</span>
                            @endforeach

                        </div>
                    </div>
                    <div class="card">
                        <div class="header bg-blue">
                            <h2>
                                TAGS
                            </h2>
                        </div>
                        <div class="body">

                            @foreach($post->tags as $tag)
                                <span class="label bg-green" style="font-size: 13px;">{{$tag->name}}
                                </span>
                            @endforeach

                        </div>
                    </div>
                <div class="card">
                        <div class="header bg-blue">
                            <h2>
                                FEATURED IMAGE
                            </h2>
                        </div>
                        <div class="body">
                            <img src="{{asset('uploads/post/'.$post->image)}}" class="img-responsive thumbnail" alt="">

                        </div>
                    </div>
                </div>
            </div>


        </div>
    </section>
@endsection

@push('js')

<!-- Select Plugin Js -->
<script src="{{asset('ui/backend/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>


<!-- TinyMCE -->
<script src="{{asset('ui/backend/plugins/tinymce/tinymce.jquery.js')}}"></script>
<script src="{{asset('ui/backend/plugins/tinymce/tinymce.js')}}"></script>


<script type="text/javascript">

    //TinyMCE
    tinymce.init({
        selector: "textarea",
        theme: "modern",
        height: 300,
        plugins: [
            'advlist autolink lists link image charmap print preview hr anchor pagebreak',
            'searchreplace wordcount visualblocks visualchars code fullscreen',
            'insertdatetime media nonbreaking save table contextmenu directionality',
            'emoticons template paste textcolor colorpicker textpattern imagetools'
        ],
        toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        toolbar2: 'print preview media | forecolor backcolor emoticons',
        image_advtab: true
    });
    tinymce.suffix = ".min";
    tinyMCE.baseURL = '{{asset('ui/backend/plugins/tinymce')}}';

</script>
@endpush